BOT_TOKEN = 'MTA3NjU0MDQwMzU4MDQxNjE4MQ.G2YuJK.BSN-XIUzKhQTyLigqz7gK2D1w_SbrBo8FQPM4k'

REDDIT_CLIENT_ID = "VMOE_kFUZiEb5ImIAHVzJQ"
REDDIT_CLIENT_SECRET = "WMarBtq0rA7BHAATaEbAH4I38lhTmw"
REDDIT_PASSWORD = "13579!#%&(kml"

PFP = "https://i.pinimg.com/originals/fd/f3/48/fdf348f198f9924ab758a7fe7b1fa10c.jpg"

BANNER = "https://i.ibb.co/vxhtYVh/aesthetic.png"

wordle_list = ['ABOUT', 'ABOVE', 'ABUSE', 'ACTOR', 'ACUTE', 'ADMIT', 'ADOPT', 'ADULT', 'AFTER', 'AGAIN', 'AGENT', 'AGREE', 'AHEAD', 'ALARM', 'ALBUM', 'ALERT', 'ALIKE', 'ALIVE', 'ALLOW', 'ALONE', 'ALONG', 'ALTER', 'AMONG', 'ANGER', 'ANGLE', 'ANGRY', 'APART', 'APPLE', 'APPLY', 'ARENA', 'ARGUE', 'ARISE', 'ARRAY', 'ASIDE', 'ASSET', 'AUDIO', 'AUDIT', 'AVOID', 'AWARD', 'AWARE', 'BADLY', 'BAKER', 'BASES', 'BASIC', 'BASIS', 'BEACH', 'BEGAN', 'BEGIN', 'BEGUN', 'BEING', 'BELOW', 'BENCH', 'BILLY', 'BIRTH', 'BLACK', 'BLAME', 'BLIND', 'BLOCK', 'BLOOD', 'BOARD', 'BOOST', 'BOOTH', 'BOUND', 'BRAIN', 'BRAND', 'BREAD', 'BREAK', 'BREED', 'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROWN', 'BUILD', 'BUILT', 'BUYER', 'CABLE', 'CALIF', 'CARRY', 'CATCH', 'CAUSE', 'CHAIN', 'CHAIR', 'CHART', 'CHASE', 'CHEAP', 'CHECK', 'CHEST', 'CHIEF', 'CHILD', 'CHINA', 'CHOSE', 'CIVIL', 'CLAIM', 'CLASS', 'CLEAN', 'CLEAR', 'CLICK', 'CLOCK', 'CLOSE', 'COACH', 'COAST', 'COULD', 'COUNT', 'COURT', 'COVER', 'CRAFT', 'CRASH', 'CREAM', 'CRIME', 'CROSS', 'CROWD', 'CROWN', 'CURVE', 'CYCLE', 'DAILY', 'DANCE', 'DATED', 'DEALT', 'DEATH', 'DEBUT', 'DELAY', 'DEPTH', 'DOING', 'DOUBT', 'DOZEN', 'DRAFT', 'DRAMA', 'DRAWN', 'DREAM', 'DRESS', 'DRILL', 'DRINK', 'DRIVE', 'DROVE', 'DYING', 'EAGER', 'EARLY', 'EARTH', 'EIGHT', 'ELITE', 'EMPTY', 'ENEMY', 'ENJOY', 'ENTER', 'ENTRY', 'EQUAL', 'ERROR', 'EVENT', 'EVERY', 'EXACT', 'EXIST', 'EXTRA', 'FAITH', 'FALSE', 'FAULT', 'FIBER', 'FIELD', 'FIFTH', 'FIFTY', 'FIGHT', 'FINAL', 'FIRST', 'FIXED', 'FLASH', 'FLEET', 'FLOOR', 'FLUID', 'FOCUS', 'FORCE', 'FORTH', 'FORTY', 'FORUM', 'FOUND', 'FRAME', 'FRANK', 'FRAUD', 'FRESH', 'FRONT', 'FRUIT', 'FULLY', 'FUNNY', 'GIANT', 'GIVEN', 'GLASS', 'GLOBE', 'GOING', 'GRACE', 'GRADE', 'GRAND', 'GRANT', 'GRASS', 'GREAT', 'GREEN', 'GROSS', 'GROUP', 'GROWN', 'GUARD', 'GUESS', 'GUEST', 'GUIDE', 'HAPPY', 'HARRY', 'HEART', 'HEAVY', 'HENCE', 'HENRY', 'HORSE', 'HOTEL', 'HOUSE', 'HUMAN', 'IDEAL', 'IMAGE', 'INDEX', 'INNER', 'INPUT', 'ISSUE', 'JAPAN', 'JIMMY', 'JOINT', 'JONES', 'JUDGE', 'KNOWN', 'LABEL', 'LARGE', 'LASER', 'LATER', 'LAUGH', 'LAYER', 'LEARN', 'LEASE', 'LEAST', 'LEAVE', 'LEGAL', 'LEVEL', 'LEWIS', 'LIGHT', 'LIMIT', 'LINKS', 'LIVES', 'LOCAL', 'LOGIC', 'LOOSE', 'LOWER', 'LUCKY', 'LUNCH', 'LYING', 'MAGIC', 'MAJOR', 'MAKER', 'MARCH', 'MARIA', 'MATCH', 'MAYBE', 'MAYOR', 'MEANT', 'MEDIA', 'METAL', 'MIGHT', 'MINOR', 'MINUS', 'MIXED', 'MODEL', 'MONEY', 'MONTH', 'MORAL', 'MOTOR', 'MOUNT', 'MOUSE', 'MOUTH', 'MOVIE', 'MUSIC', 'NEEDS', 'NEVER', 'NEWLY', 'NIGHT', 'NOISE', 'NORTH', 'NOTED', 'NOVEL', 'NURSE', 'OCCUR', 'OCEAN', 'OFFER', 'OFTEN', 'ORDER', 'OTHER', 'OUGHT', 'PAINT', 'PANEL', 'PAPER', 'PARTY', 'PEACE', 'PETER', 'PHASE', 'PHONE', 'PHOTO', 'PIECE', 'PILOT', 'PITCH', 'PLACE', 'PLAIN', 'PLANE', 'PLANT', 'PLATE', 'POINT', 'POUND', 'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIME', 'PRINT', 'PRIOR', 'PRIZE', 'PROOF', 'PROUD', 'PROVE', 'QUEEN', 'QUICK', 'QUIET', 'QUITE', 'RADIO', 'RAISE', 'RANGE', 'RAPID', 'RATIO', 'REACH', 'READY', 'REFER', 'RIGHT', 'RIVAL', 'RIVER', 'ROBIN', 'ROGER', 'ROMAN', 'ROUGH', 'ROUND', 'ROUTE', 'ROYAL', 'RURAL', 'SCALE', 'SCENE', 'SCOPE', 'SCORE', 'SENSE', 'SERVE', 'SEVEN', 'SHALL', 'SHAPE', 'SHARE', 'SHARP', 'SHEET', 'SHELF', 'SHELL', 'SHIFT', 'SHIRT', 'SHOCK', 'SHOOT', 'SHORT', 'SHOWN', 'SIGHT', 'SINCE', 'SIXTH', 'SIXTY', 'SIZED', 'SKILL', 'SLEEP', 'SLIDE', 'SMALL', 'SMART', 'SMILE', 'SMITH', 'SMOKE', 'SOLID', 'SOLVE', 'SORRY', 'SOUND', 'SOUTH', 'SPACE', 'SPARE', 'SPEAK', 'SPEED', 'SPEND', 'SPENT', 'SPLIT', 'SPOKE', 'SPORT', 'STAFF', 'STAGE', 'STAKE', 'STAND', 'START', 'STATE', 'STEAM', 'STEEL', 'STICK', 'STILL', 'STOCK', 'STONE', 'STOOD', 'STORE', 'STORM', 'STORY', 'STRIP', 'STUCK', 'STUDY', 'STUFF', 'STYLE', 'SUGAR', 'SUITE', 'SUPER', 'SWEET', 'TABLE', 'TAKEN', 'TASTE', 'TAXES', 'TEACH', 'TEETH', 'TERRY', 'TEXAS', 'THANK', 'THEFT', 'THEIR', 'THEME', 'THERE', 'THESE', 'THICK', 'THING', 'THINK', 'THIRD', 'THOSE', 'THREE', 'THREW', 'THROW', 'TIGHT', 'TIMES', 'TIRED', 'TITLE', 'TODAY', 'TOPIC', 'TOTAL', 'TOUCH', 'TOUGH', 'TOWER', 'TRACK', 'TRADE', 'TRAIN', 'TREAT', 'TREND', 'TRIAL', 'TRIED', 'TRIES', 'TRUCK', 'TRULY', 'TRUST', 'TRUTH', 'TWICE', 'UNDER', 'UNDUE', 'UNION', 'UNITY', 'UNTIL', 'UPPER', 'UPSET', 'URBAN', 'USAGE', 'USUAL', 'VALID', 'VALUE', 'VIDEO', 'VIRUS', 'VISIT', 'VITAL', 'VOICE', 'WASTE', 'WATCH', 'WATER', 'WHEEL', 'WHERE', 'WHICH', 'WHILE', 'WHITE', 'WHOLE', 'WHOSE', 'WOMAN', 'WOMEN', 'WORLD', 'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD', 'WOUND', 'WRITE', 'WRONG', 'WROTE', 'YIELD', 'YOUNG', 'YOUTH']

COMMANDS = ['+help kick', '+help ban', '+help timeout', '+kick', '+ban', '+timeout', '+coin_toss', '+rps', '+scramble',
            '+joke', '+meme', '+animal', '+help coin_toss', '+help rps', '+help scramble', '+help joke', '+help meme',
            '+help animal', '+help join', '+help, play', '+join', '+disconnect', '+play', '+pause', '+resume', '+role',
            '+user', '+nick', '+translate', '+help disconnect', '+help pause', '+help resume', '+help role',
            '+help calculator', '+help poll', '+calculator', '+poll', '+timer', '+reminder', '+coin', '+toss',
            '+k', '+b', '+help timer', '+help reminder', '+ct', '+scram', '+j', '+m', '+a', '+an', '+hi',
            '+bye', '+dc', '+p', '+r', '+n', '+u', '+trans', '+calc', '+c', '+stop', '+help', '+wordle', '+ban_list',
            '+bl', '+unban', '+remind', '+wd', '+t', '+time']

words = ["a", "able", "about", "above", "across", "act", "actor", "active", "activity", "add", "afraid",
         "after",
         "again", "age", "ago", "agree", "air", "all", "alone", "along", "already", "always", "am", "amount",
         "an",
         "and", "angry", "another", "answer", "any", "anyone", "anything", "anytime", "appear", "apple", "are",
         "area",
         "arm", "army", "around", "arrive", "art", "as", "ask", "at", "attack", "aunt", "autumn",
         "away", "baby", "base", "back", "bad", "bag", "ball", "bank", "basket", "bath", "be", "bean", "bear",
         "beautiful", "beer", "bed", "bedroom", "behave", "before", "begin", "behind", "bell", "below",
         "besides",
         "best", "better", "between", "big", "bird", "birth", "birthday", "bit", "bite", "black", "bleed",
         "block",
         "blood", "blow", "blue", "board", "boat", "body", "boil", "bone", "book", "border", "born", "borrow",
         "both",
         "bottle", "bottom", "bowl", "box", "boy", "branch", "brave", "bread", "break", "breakfast", "breathe",
         "bridge", "bright", "bring", "brother", "brown", "brush", "build", "burn", "business", "bus", "busy",
         "but",
         "buy", "by", "bundle", "cake", "call", "can", "candle", "cap", "car", "card", "care", "careful",
         "careless",
         "carry", "case", "cat", "catch", "central", "century", "certain", "chair", "chance", "change", "chase",
         "cheap", "cheese", "chicken", "child", "children", "chocolate", "choice", "choose", "circle", "city",
         "class",
         "clever", "clean", "clear", "climb", "clock", "cloth", "clothes", "cloud", "cloudy", "close", "coffee",
         "coat",
         "coin", "cold", "collect", "colour", "comb", "come", "comfortable", "common", "compare", "complete",
         "computer", "condition", "continue", "control", "cook", "cool", "copper", "corn", "corner", "correct",
         "cost",
         "contain", "count", "country", "course", "cover", "crash", "cross", "cry", "cup", "cupboard", "cut",
         "dance",
         "danger", "dangerous", "dark", "daughter", "day", "dead", "decide", "decrease", "deep", "deer",
         "depend",
         "desk", "destroy", "develop", "die", "different", "difficult", "dinner", "direction", "dirty",
         "discover",
         "dish", "do", "dog", "door", "double", "down", "draw", "dream", "dress", "drink", "drive", "drop",
         "dry",
         "duck", "dust", "duty", "destroy", "dedicated", "each", "ear", "early", "earn", "earth", "east",
         "easy", "eat",
         "education", "effect", "egg", "eight", "either", "electric", "elephant", "else", "empty", "end",
         "enemy",
         "enjoy", "enough", "enter", "equal", "entrance", "escape", "even", "evening", "event", "ever", "every",
         "everyone", "exact", "everybody", "examination", "example", "except", "excited", "exercise", "expect",
         "expensive", "explain", "extremely", "eye", "face", "fact", "fail", "fall", "false", "family",
         "famous", "far",
         "farm", "father", "fast", "fat", "fault", "fear", "feed", "feel", "female", "fever", "few", "fight",
         "fill",
         "film", "find", "fine", "finger", "finish", "fire", "first", "fit", "five", "fix", "flag", "flat",
         "float",
         "floor", "flour", "flower", "fly", "fold", "food", "fool", "foot", "football", "for", "force",
         "foreign",
         "forest", "forget", "forgive", "fork", "form", "fox", "four", "free", "freedom", "freeze", "fresh",
         "friend",
         "friendly", "from", "front", "fruit", "full", "fun", "funny", "furniture", "further", "future", "game",
         "garden", "gate", "general", "gentleman", "get", "gift", "give", "glad", "glass", "go", "goat", "god",
         "gold",
         "good", "goodbye", "grandfather", "grandmother", "grass", "grave", "great", "green", "grey", "ground",
         "group",
         "grow", "gun", "hair", "half", "hall", "hammer", "hand", "happen", "happy", "hard", "hat", "hate",
         "have",
         "he", "head", "healthy", "hear", "heavy", "hello", "help", "heart", "heaven", "height", "hen", "her",
         "here",
         "hers", "hide", "high", "hill", "him", "his", "hit", "hobby", "hold", "hole", "holiday", "home",
         "hope",
         "horse", "hospital", "hot", "hotel", "house", "how", "hundred", "hungry", "hour", "hurry", "husband",
         "hurt",
         "I", "ice", "idea", "if", "important", "in", "increase", "inside", "into", "introduce", "invent",
         "iron",
         "invite", "is", "island", "it", "its", "job", "join", "juice", "jump", "just", "keep", "key", "kid",
         "kill",
         "kind", "king", "kitchen", "knee", "knife", "knock", "know", "ladder", "lady", "lamp", "land", "large",
         "last",
         "late", "lately", "laugh", "lazy", "lead", "leaf", "learn", "leave", "leg", "left", "lend", "length",
         "less",
         "lesson", "let", "letter", "library", "lie", "life", "light", "like", "lion", "lip", "list", "listen",
         "little", "live", "lock", "lonely", "long", "look", "lose", "lot", "love", "low", "lower", "luck",
         "machine",
         "main", "make", "male", "man", "many", "map", "mark", "market", "marry", "matter", "may", "me", "meal",
         "mean",
         "measure", "meat", "medicine", "meet", "member", "mention", "method", "middle", "milk", "mill",
         "million",
         "mind", "mine", "minute", "miss", "mistake", "mix", "model", "modern", "moment", "money", "monkey",
         "month",
         "moon", "more", "morning", "most", "mother", "mountain", "mouse", "mouth", "move", "much", "music",
         "must",
         "my", "name", "narrow", "nation", "nature", "near", "nearly", "neck", "need", "needle", "neighbour",
         "neither",
         "net", "never", "new", "news", "newspaper", "next", "nice", "night", "nine", "no", "noble", "noise",
         "none",
         "nor", "north", "nose", "not", "nothing", "notice", "now", "number", "obey", "object", "ocean", "of",
         "off",
         "offer", "office", "often", "oil", "old", "on", "one", "only", "open", "opposite", "or", "orange",
         "order",
         "other", "our", "out", "outside", "over", "own", "page", "pain", "paint", "pair", "pan", "paper",
         "parent",
         "park", "part", "partner", "party", "pass", "past", "path", "pay", "peace", "pen", "pencil", "people",
         "pepper", "per", "perfect", "period", "person", "petrol", "photograph", "piano", "pick", "picture",
         "piece",
         "pig", "pill", "pin", "pink", "place", "plane", "plant", "plastic", "plate", "play", "please",
         "pleased",
         "plenty", "pocket", "point", "poison", "police", "polite", "pool", "poor", "popular", "position",
         "possible",
         "potato", "pour", "power", "present", "press", "pretty", "prevent", "price", "prince", "prison",
         "private",
         "prize", "probably", "problem", "produce", "promise", "proper", "protect", "provide", "public", "pull",
         "punish", "pupil", "push", "put", "queen", "question", "quick", "quiet", "quite", "radio", "rain",
         "rainy",
         "raise", "reach", "read", "ready", "real", "really", "receive", "record", "red", "remember", "remind",
         "remove", "rent", "repair", "repeat", "reply", "report", "rest", "restaurant", "result", "return",
         "rice",
         "rich", "ride", "right", "ring", "rise", "road", "rob", "rock", "room", "round", "rubber", "rude",
         "rule",
         "ruler", "run", "rush", "sad", "safe", "sail", "salt", "same", "sand", "save", "say", "school",
         "science",
         "scissors", "search", "seat", "second", "see", "seem", "sell", "send", "sentence", "serve", "seven",
         "several",
         "sex", "shade", "shadow", "shake", "shape", "share", "sharp", "she", "sheep", "sheet", "shelf",
         "shine",
         "ship", "shirt", "shoe", "shoot", "shop", "short", "should", "shoulder", "shout", "show", "sick",
         "side",
         "signal", "silence", "silly", "silver", "similar", "simple", "single", "since", "sing", "sink",
         "sister",
         "sit", "six", "size", "skill", "skin", "skirt", "sky", "sleep", "slip", "slow", "small", "smell",
         "smile",
         "smoke", "snow", "so", "soap", "sock", "soft", "some", "someone", "something", "sometimes", "son",
         "soon",
         "sorry", "sound", "soup", "south", "space", "speak", "special", "speed", "spell", "spend", "spoon",
         "sport",
         "spread", "spring", "square", "stamp", "stand", "star", "start", "station", "stay", "steal", "steam",
         "step",
         "still", "stomach", "stone", "stop", "store", "storm", "story", "strange", "street", "strong",
         "structure",
         "student", "study", "stupid", "subject", "substance", "successful", "such", "sudden", "sugar",
         "suitable",
         "summer", "sun", "sunny", "support", "sure", "surprise", "sweet", "swim", "sword", "table", "take",
         "talk",
         "tall", "taste", "taxi", "tea", "teach", "team", "tear", "telephone", "television", "tell", "ten",
         "tennis",
         "terrible", "test", "than", "that", "the", "their", "theirs", "then", "there", "therefore", "these",
         "thick",
         "thin", "thing", "think", "third", "this", "those", "though", "threat", "three", "tidy", "tie",
         "title", "to",
         "today", "toe", "together", "tomorrow", "tonight", "too", "tool", "tooth", "top", "total", "touch",
         "town",
         "train", "tram", "travel", "tree", "trouble", "true", "trust", "twice", "try", "turn", "type", "under",
         "uncle", "understand", "unit", "until", "up", "use", "useful", "usual", "usually", "vegetable", "very",
         "village", "voice", "visit", "value", "vacuum", "vampire", "verb", "validation", "wait", "wake",
         "walk",
         "want", "warm", "wash", "waste", "watch", "water", "way", "we", "weak", "wear", "weather", "wedding",
         "week",
         "weight", "welcome", "well", "west", "wet", "what", "wheel", "when", "where", "which", "while",
         "white",
         "who", "why", "wide", "wife", "wild", "will", "win", "wind", "window", "wine", "winter", "wire",
         "wise",
         "wish", "with", "without", "woman", "wonder", "word", "work", "world", "worry", "worst", "write",
         "wrong",
         "year", "yellow", "yes", "yesterday", "yet", "you", "young", "your", "yours", "zero", "zoo", "zoom"]

banned_words = ["Nigga", "nigga", "Nigger", "nigger, ",
                        "Faggot", "faggot", "coon", "Coon",
                        "Rape", "rape", "Retard", "retard", "Pedo", "pedo"]  # more words can be added

country_dict = {'ascension island': '🇦🇨', 'andorra': '🇦🇩', 'united arab emirates': '🇦🇪', 'afghanistan': '🇦🇫',
                'antigua and barbuda': '🇦🇬', 'anguilla': '🇦🇮', 'albania': '🇦🇱', 'armenia': '🇦🇲',
                'angola': '🇦🇴', 'antarctica': '🇦🇶', 'argentina': '🇦🇷', 'american samoa': '🇦🇸',
                'austria': '🇦🇹', 'australia': '🇦🇺', 'aruba': '🇦🇼', 'azerbaijan': '🇦🇿', 'bosnia and herzegovina': '🇧🇦',
                'barbados': '🇧🇧', 'bangladesh': '🇧🇩', 'belgium': '🇧🇪', 'burkina faso': '🇧🇫', 'bulgaria': '🇧🇬',
                'bahrain': '🇧🇭', 'burundi': '🇧🇮', 'benin': '🇧🇯', 'bermuda': '🇧🇲', 'brunei': '🇧🇳', 'bolivia': '🇧🇴',
                'caribbean netherlands': '🇧🇶', 'brazil': '🇧🇷', 'bahamas': '🇧🇸', 'bhutan': '🇧🇹', 'bouvet island': '🇧🇻',
                'botswana': '🇧🇼', 'belarus': '🇧🇾', 'belize': '🇧🇿', 'canada': '🇨🇦', 'cocos islands': '🇨🇨',
                'central african republic': '🇨🇫', 'switzerland': '🇨🇭', 'cook islands': '🇨🇰', 'chile': '🇨🇱',
                'cameroon': '🇨🇲', 'china': '🇨🇳', 'colombia': '🇨🇴', 'clipperton island': '🇨🇵', 'costa rica': '🇨🇷',
                'cuba': '🇨🇺', 'cape verde': '🇨🇻', 'christmas island': '🇨🇽', 'cyprus': '🇨🇾', 'czechia': '🇨🇿',
                'germany': '🇩🇪', 'diego garcia': '🇩🇬', 'djibouti': '🇩🇯', 'denmark': '🇩🇰', 'dominica': '🇩🇲',
                'dominican republic': '🇩🇴', 'algeria': '🇩🇿', 'cueta and melilla': '🇪🇦', 'ecuador': '🇪🇨',
                'estonia': '🇪🇪', 'egypt': '🇪🇬', 'western sahara': '🇪🇭', 'eritrea': '🇪🇷', 'spain': '🇪🇸', 'ethiopia': '🇪🇹',
                'european union': '🇪🇺', 'finland': '🇫🇮', 'fiji': '🇫🇯', 'falkland islands': '🇫🇰', 'micronesia': '🇫🇲',
                'faroe islands': '🇫🇴', 'france': '🇫🇷', 'gabon': '🇬🇦', 'united kingdom': '🇬🇧', 'grenada': '🇬🇩',
                'georgia': '🇬🇪', 'french guiana': '🇬🇫', 'guernsey': '🇬🇬', 'ghana': '🇬🇭', 'gibraltar': '🇬🇮',
                'greenland': '🇬🇱', 'gambia': '🇬🇲', 'guinea': '🇬🇳', 'guadeloupe': '🇬🇵', 'equatorial guinea': '🇬🇶',
                'greece': '🇬🇷', 'guatemala': '🇬🇹', 'guam': '🇬🇺', 'guinea-bissau': '🇬🇼', 'guyana': '🇬🇾', 'hong kong': '🇭🇰',
                'heard and mcdonald islands': '🇭🇲', 'honduras': '🇭🇳', 'croatia': '🇭🇷', 'haiti': '🇭🇹', 'hungary': '🇭🇺',
                'canary islands': '🇮🇨', 'indonesia': '🇮🇩', 'ireland': '🇮🇪', 'israel': '🇮🇱', 'isle of man': '🇮🇲',
                'india': '🇮🇳', 'british indian ocean territory': '🇮🇴', 'iraq': '🇮🇶', 'iran': '🇮🇷', 'iceland': '🇮🇸',
                'italy': '🇮🇹', 'jersey': '🇯🇪', 'jamaica': '🇯🇲', 'jordan': '🇯🇴', 'japan': '🇯🇵', 'kenya': '🇰🇪',
                'kyrgyzstan': '🇰🇬', 'cambodia': '🇰🇭', 'kiribati': '🇰🇮', 'comoros': '🇰🇲', 'st. kitts and nevis': '🇰🇳',
                'north korea': '🇰🇵', 'south korea': '🇰🇷', 'kuwait': '🇰🇼', 'cayman islands': '🇰🇾', 'kazakhstan': '🇰🇿',
                'laos': '🇱🇦', 'lebanon': '🇱🇧', 'st. lucia': '🇱🇨', 'liechtenstein': '🇱🇮', 'sri lanka': '🇱🇰', 'liberia': '🇱🇷',
                'lesotho': '🇱🇸', 'lithuania': '🇱🇹', 'luxembourg': '🇱🇺', 'latvia': '🇱🇻', 'libya': '🇱🇾', 'morocco': '🇲🇦',
                'monaco': '🇲🇨', 'moldova': '🇲🇩', 'montenegro': '🇲🇪', 'st. martin': '🇲🇫', 'madagascar': '🇲🇬',
                'marshall islands': '🇲🇭', 'north macedonia': '🇲🇰', 'mali': '🇲🇱', 'myanmar': '🇲🇲', 'mongolia': '🇲🇳',
                'macao sar china': '🇲🇴', 'northern mariana islands': '🇲🇵', 'martinique': '🇲🇶', 'mauritania': '🇲🇷',
                'montserrat': '🇲🇸', 'malta': '🇲🇹', 'mauritius': '🇲🇺', 'maldives': '🇲🇻', 'malawi': '🇲🇼', 'mexico': '🇲🇽',
                'malaysia': '🇲🇾', 'mozambique': '🇲🇿', 'namibia': '🇳🇦', 'new caledonia': '🇳🇨', 'niger': '🇳🇪',
                'norfolk island': '🇳🇫', 'nigeria': '🇳🇬', 'nicaragua': '🇳🇮', 'netherlands': '🇳🇱', 'norway': '🇳🇴',
                'nepal': '🇳🇵', 'nauru': '🇳🇷', 'niue': '🇳🇺', 'new zealand': '🇳🇿', 'oman': '🇴🇲', 'panama': '🇵🇦',
                'peru': '🇵🇪', 'french polynesia': '🇵🇫', 'papua new guinea': '🇵🇬', 'philippines': '🇵🇭', 'pakistan': '🇵🇰',
                'poland': '🇵🇱', 'st. pierre and miquelon': '🇵🇲', 'pitcairn islands': '🇵🇳', 'puerto rico': '🇵🇷',
                'palestinian territories': '🇵🇸', 'portugal': '🇵🇹', 'palau': '🇵🇼', 'paraguay': '🇵🇾', 'qatar': '🇶🇦',
                'reunion': '🇷🇪', 'romania': '🇷🇴', 'serbia': '🇷🇸', 'russia': '🇷🇺', 'rwanda': '🇷🇼', 'saudi arabia': '🇸🇦',
                'solomon islands': '🇸🇧', 'seychelles': '🇸🇨', 'sudan': '🇸🇩', 'sweden': '🇸🇪', 'singapore': '🇸🇬',
                'st. helena': '🇸🇭', 'slovenia': '🇸🇮', 'svalbard and jan mayen': '🇸🇯', 'slovakia': '🇸🇰',
                'sierra leone': '🇸🇱', 'san marino': '🇸🇲', 'senegal': '🇸🇳', 'somalia': '🇸🇴', 'suriname': '🇸🇷',
                'south sudan': '🇸🇸', 'el salvador': '🇸🇻', 'sint maarten': '🇸🇽', 'syria': '🇸🇾', 'eswatini': '🇸🇿',
                'tristan da cunha': '🇹🇦', 'turks and caicos islands': '🇹🇨', 'chad': '🇹🇩',
                'french southern territories': '🇹🇫', 'togo': '🇹🇬', 'thailand': '🇹🇭', 'tajikistan': '🇹🇯', 'tokelau': '🇹🇰',
                'timor-leste': '🇹🇱', 'turkmenistan': '🇹🇲', 'tunisia': '🇹🇳', 'tonga': '🇹🇴', 'turkey': '🇹🇷',
                'trinidad and tobago': '🇹🇹', 'tuvalu': '🇹🇻', 'taiwan': '🇹🇼', 'tanzania': '🇹🇿', 'ukraine': '🇺🇦',
                'uganda': '🇺🇬', 'united nations': '🇺🇳', 'united states': '🇺🇸', 'uruguay': '🇺🇾', 'uzbekistan': '🇺🇿',
                'vatican city': '🇻🇦', 'st. vincent and grenadines': '🇻🇨', 'venezuela': '🇻🇪',
                'british virgin islands': '🇻🇬', 'us virgin islands': '🇻🇮', 'vietnam': '🇻🇳', 'vanuatu': '🇻🇺',
                'wallis and futuna': '🇼🇫', 'samoa': '🇼🇸', 'kosovo': '🇽🇰', 'yemen': '🇾🇪', 'mayotte': '🇾🇹',
                'south africa': '🇿🇦', 'zambia': '🇿🇲', 'zimbabwe': '🇿🇼'}
